### ISSUE TITLE
Location metadata

### ISSUE THREAD

**Issue by mhmmsips** [cal-overflow/memory-download#42]
Best ChristianLisle,

Right now, the pictures and videos do not have the location metadata attached to them. Is there a possibility to make this a feature?

**Comment by ChristianLisle** [comment]
I will look into adding this feature. I'm not sure if this is possible, since the `memories_history.json` file only includes the date/time metadata of the memories.

There is a `location_history.json` file included in the Snapchat data download that might allow for a feature like this. I'll look into this shortly.

**Comment by mhmmsips** [comment]
Cool! Let me know whenever you have tried to figure this out. Really want to get updated since it would be a great feature. Good luck!

**Comment by ChristianLisle** [comment]
After looking through the data Snapchat provides you in your data download, I don't think this is possible. It seems that the `location_history.json` file includes locations that are not related to memories in any way, but instead other geolocation features of the app. I also noticed that the locations in the `location_history.json` file were inaccurate, as it showed records of me being in places on completely inaccurate dates.

I will reach out to Snapchat to see if there's some way to find the location metadata that belongs to the memories. I'll respond here once I find out more

**Comment by ChristianLisle** [comment]
I have reached out to the Snapchat support team numerous times with no response 😕

I'll keep trying to contact them and post updates here.
